name: 'Generate Release'

on:
  push:
    branches:
	    - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # 現有的 GitHub 官方 Action。將專案程式碼 Checkout，接著可進行測試，部署等。

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      # 建立 Node.js 環境，因為 semantic-release 通常依賴 Node.js。

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
      - name: Install dependencies
        run: pnpm install
      # pnpm install 以執行 semantic-release。

      - name: Run Semantic Release
        uses: semantic-release/semantic-release@v19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # 使用 semantic-release 自動管理版本號和創 GitHub Release。
